Config:
    mensaje-bienvenida: true
    mensaje-bienvenida-texto: 
    - "Bievenido a mi primer plugin "
    - "Creado por Jorge Carrera Diez"
    - "Disfrutalo"
Spawn:
    x:
    y:
    z:
    yaw:
    pitch: